### ISSUE TITLE
my build is failing

### ISSUE THREAD

**Issue by shvhh** [postor/docker-ionic-android-build#1]
here is the complete log

<div class="build-trace-container position-relative prepend-top-default"><div class="top-bar sidebar-collapsed"><div class="js-truncated-info truncated-info d-none d-sm-block float-left"></div> <div class="controllers float-right"><a title="Show complete raw" href="/hemantrajput19/android-build-test/-/jobs/568550534/raw" class="gl-link js-raw-link-controller controllers-buttons"><svg aria-hidden="true" class="s16 ic-doc-text"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#doc-text"></use></svg></a> <a title="Erase job log" data-confirm="Are you sure you want to erase this build?" data-method="post" href="/hemantrajput19/android-build-test/-/jobs/568550534/erase" class="gl-link js-erase-link controllers-buttons"><svg aria-hidden="true" class="s16 ic-remove"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#remove"></use></svg></a> <div title="Scroll to top" class="controllers-buttons"><button type="button" class="btn js-scroll-top btn-scroll btn-transparent btn-blank btn-secondary btn-md disabled" disabled="disabled"> <svg aria-hidden="true" class="s16 ic-scroll_up"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#scroll_up"></use></svg></button></div> <div title="Scroll to bottom" class="controllers-buttons"><button type="button" class="btn js-scroll-bottom btn-scroll btn-transparent btn-blank btn-secondary btn-md"><svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path class="scroll-arrow" d="M8 10.4142L4.29289 6.70711C3.90237 6.31658 3.90237 5.68342 4.29289 5.2929C4.68342 4.90237 5.31658 4.90237 5.70711 5.2929L7 6.58579L7 1C7 0.447715 7.44772 0 8 0C8.55229 0 9 0.447715 9 1L9 6.58579L10.2929 5.2929C10.6834 4.90237 11.3166 4.90237 11.7071 5.2929C12.0976 5.68342 12.0976 6.31658 11.7071 6.70711L8 10.4142Z"></path>
<path class="scroll-dot" d="M8 16C9.10457 16 10 15.1046 10 14C10 12.8954 9.10457 12 8 12C6.89543 12 6 12.8954 6 14C6 15.1046 6.89543 16 8 16Z"></path>
</svg>
</button></div></div></div> <code data-qa-selector="job_log_content" class="job-log d-block" trace="[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]" is-complete="true"><div class="js-line log-line"><a id="L1" href="/hemantrajput19/android-build-test/-/jobs/568550534#L1" class="gl-link d-inline-block text-right line-number flex-shrink-0">1</a> <span class="ws-pre-wrap">Running with gitlab-runner 13.0.0-rc2 (926834bc)</span></div><div class="js-line log-line"><a id="L2" href="/hemantrajput19/android-build-test/-/jobs/568550534#L2" class="gl-link d-inline-block text-right line-number flex-shrink-0">2</a> <span class="ws-pre-wrap">  on docker-auto-scale ed2dce3a</span></div><div><div role="button" class="log-line collapsible-line d-flex justify-content-between ws-normal"><svg aria-hidden="true" class="arrow position-absolute s16 ic-angle-down"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#angle-down"></use></svg> <a id="L3" href="/hemantrajput19/android-build-test/-/jobs/568550534#L3" class="gl-link d-inline-block text-right line-number flex-shrink-0">3</a> <span class="line-text w-100 ws-pre-wrap term-fg-l-cyan term-bold">Preparing the "docker+machine" executor</span> </div> <div class="js-line log-line"><a id="L4" href="/hemantrajput19/android-build-test/-/jobs/568550534#L4" class="gl-link d-inline-block text-right line-number flex-shrink-0">4</a> <span class="ws-pre-wrap">Using Docker executor with image postor/ionic-android-build ...</span></div><div class="js-line log-line"><a id="L5" href="/hemantrajput19/android-build-test/-/jobs/568550534#L5" class="gl-link d-inline-block text-right line-number flex-shrink-0">5</a> <span class="ws-pre-wrap">Pulling docker image postor/ionic-android-build ...</span></div><div class="js-line log-line"><a id="L6" href="/hemantrajput19/android-build-test/-/jobs/568550534#L6" class="gl-link d-inline-block text-right line-number flex-shrink-0">6</a> <span class="ws-pre-wrap">Using docker image sha256:3373fadc8f0510e1ac93e119f54eb24ed557d98d86488ea7cefe36b732a4a602 for postor/ionic-android-build ...</span></div></div><div><div role="button" class="log-line collapsible-line d-flex justify-content-between ws-normal"><svg aria-hidden="true" class="arrow position-absolute s16 ic-angle-down"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#angle-down"></use></svg> <a id="L7" href="/hemantrajput19/android-build-test/-/jobs/568550534#L7" class="gl-link d-inline-block text-right line-number flex-shrink-0">7</a> <span class="line-text w-100 ws-pre-wrap term-fg-l-cyan term-bold">Preparing environment</span> <div class="log-duration-badge rounded align-self-start px-2 ml-2 flex-shrink-0 ws-normal">
  00:06
</div></div> <div class="js-line log-line"><a id="L8" href="/hemantrajput19/android-build-test/-/jobs/568550534#L8" class="gl-link d-inline-block text-right line-number flex-shrink-0">8</a> <span class="ws-pre-wrap">Running on runner-ed2dce3a-project-19016821-concurrent-0 via runner-ed2dce3a-srm-1590525947-e5d95805...</span></div></div><div><div role="button" class="log-line collapsible-line d-flex justify-content-between ws-normal"><svg aria-hidden="true" class="arrow position-absolute s16 ic-angle-down"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#angle-down"></use></svg> <a id="L9" href="/hemantrajput19/android-build-test/-/jobs/568550534#L9" class="gl-link d-inline-block text-right line-number flex-shrink-0">9</a> <span class="line-text w-100 ws-pre-wrap term-fg-l-cyan term-bold">Getting source from Git repository</span> <div class="log-duration-badge rounded align-self-start px-2 ml-2 flex-shrink-0 ws-normal">
  00:03
</div></div> <div class="js-line log-line"><a id="L10" href="/hemantrajput19/android-build-test/-/jobs/568550534#L10" class="gl-link d-inline-block text-right line-number flex-shrink-0">10</a> <span class="ws-pre-wrap term-fg-l-green term-bold">$ eval "$CI_PRE_CLONE_SCRIPT"</span></div><div class="js-line log-line"><a id="L11" href="/hemantrajput19/android-build-test/-/jobs/568550534#L11" class="gl-link d-inline-block text-right line-number flex-shrink-0">11</a> <span class="ws-pre-wrap term-fg-l-green term-bold">Fetching changes with git depth set to 50...</span></div><div class="js-line log-line"><a id="L12" href="/hemantrajput19/android-build-test/-/jobs/568550534#L12" class="gl-link d-inline-block text-right line-number flex-shrink-0">12</a> <span class="ws-pre-wrap">Initialized empty Git repository in /builds/hemantrajput19/android-build-test/.git/</span></div><div class="js-line log-line"><a id="L13" href="/hemantrajput19/android-build-test/-/jobs/568550534#L13" class="gl-link d-inline-block text-right line-number flex-shrink-0">13</a> <span class="ws-pre-wrap term-fg-l-green term-bold">Created fresh repository.</span></div><div class="js-line log-line"><a id="L14" href="/hemantrajput19/android-build-test/-/jobs/568550534#L14" class="gl-link d-inline-block text-right line-number flex-shrink-0">14</a> <span class="ws-pre-wrap">From https://gitlab.com/hemantrajput19/android-build-test</span></div><div class="js-line log-line"><a id="L15" href="/hemantrajput19/android-build-test/-/jobs/568550534#L15" class="gl-link d-inline-block text-right line-number flex-shrink-0">15</a> <span class="ws-pre-wrap"> * [new ref]         refs/pipelines/149859656 -&gt; refs/pipelines/149859656</span></div><div class="js-line log-line"><a id="L16" href="/hemantrajput19/android-build-test/-/jobs/568550534#L16" class="gl-link d-inline-block text-right line-number flex-shrink-0">16</a> <span class="ws-pre-wrap"> * [new branch]      master                   -&gt; origin/master</span></div><div class="js-line log-line"><a id="L17" href="/hemantrajput19/android-build-test/-/jobs/568550534#L17" class="gl-link d-inline-block text-right line-number flex-shrink-0">17</a> <span class="ws-pre-wrap term-fg-l-green term-bold">Checking out 01b1b085 as master...</span></div><div class="js-line log-line"><a id="L18" href="/hemantrajput19/android-build-test/-/jobs/568550534#L18" class="gl-link d-inline-block text-right line-number flex-shrink-0">18</a> <span class="ws-pre-wrap term-fg-l-green term-bold">Skipping Git submodules setup</span></div></div><div><div role="button" class="log-line collapsible-line d-flex justify-content-between ws-normal"><svg aria-hidden="true" class="arrow position-absolute s16 ic-angle-down"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#angle-down"></use></svg> <a id="L19" href="/hemantrajput19/android-build-test/-/jobs/568550534#L19" class="gl-link d-inline-block text-right line-number flex-shrink-0">19</a> <span class="line-text w-100 ws-pre-wrap term-fg-l-cyan term-bold">Restoring cache</span> <div class="log-duration-badge rounded align-self-start px-2 ml-2 flex-shrink-0 ws-normal">
  00:01
</div></div> </div><div><div role="button" class="log-line collapsible-line d-flex justify-content-between ws-normal"><svg aria-hidden="true" class="arrow position-absolute s16 ic-angle-down"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#angle-down"></use></svg> <a id="L20" href="/hemantrajput19/android-build-test/-/jobs/568550534#L20" class="gl-link d-inline-block text-right line-number flex-shrink-0">20</a> <span class="line-text w-100 ws-pre-wrap term-fg-l-cyan term-bold">Downloading artifacts</span> <div class="log-duration-badge rounded align-self-start px-2 ml-2 flex-shrink-0 ws-normal">
  00:02
</div></div> </div><div><div role="button" class="log-line collapsible-line d-flex justify-content-between ws-normal"><svg aria-hidden="true" class="arrow position-absolute s16 ic-angle-down"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#angle-down"></use></svg> <a id="L21" href="/hemantrajput19/android-build-test/-/jobs/568550534#L21" class="gl-link d-inline-block text-right line-number flex-shrink-0">21</a> <span class="line-text w-100 ws-pre-wrap term-fg-l-cyan term-bold">Running before_script and script</span> </div> <div class="js-line log-line"><a id="L22" href="/hemantrajput19/android-build-test/-/jobs/568550534#L22" class="gl-link d-inline-block text-right line-number flex-shrink-0">22</a> <span class="ws-pre-wrap term-fg-l-green term-bold">$ yarn</span></div><div class="js-line log-line"><a id="L23" href="/hemantrajput19/android-build-test/-/jobs/568550534#L23" class="gl-link d-inline-block text-right line-number flex-shrink-0">23</a> <span class="ws-pre-wrap">yarn install v1.9.4</span></div><div class="js-line log-line"><a id="L24" href="/hemantrajput19/android-build-test/-/jobs/568550534#L24" class="gl-link d-inline-block text-right line-number flex-shrink-0">24</a> <span class="ws-pre-wrap">info No lockfile found.</span></div><div class="js-line log-line"><a id="L25" href="/hemantrajput19/android-build-test/-/jobs/568550534#L25" class="gl-link d-inline-block text-right line-number flex-shrink-0">25</a> <span class="ws-pre-wrap">[1/4] Resolving packages...</span></div><div class="js-line log-line"><a id="L26" href="/hemantrajput19/android-build-test/-/jobs/568550534#L26" class="gl-link d-inline-block text-right line-number flex-shrink-0">26</a> <span class="ws-pre-wrap">warning @testing-library/jest-dom &gt; css &gt; urix@0.1.0: Please see https://github.com/lydell/urix#deprecated</span></div><div class="js-line log-line"><a id="L27" href="/hemantrajput19/android-build-test/-/jobs/568550534#L27" class="gl-link d-inline-block text-right line-number flex-shrink-0">27</a> <span class="ws-pre-wrap">warning @testing-library/jest-dom &gt; css &gt; source-map-resolve &gt; urix@0.1.0: Please see https://github.com/lydell/urix#deprecated</span></div><div class="js-line log-line"><a id="L28" href="/hemantrajput19/android-build-test/-/jobs/568550534#L28" class="gl-link d-inline-block text-right line-number flex-shrink-0">28</a> <span class="ws-pre-wrap">warning @testing-library/jest-dom &gt; css &gt; source-map-resolve &gt; resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated</span></div><div class="js-line log-line"><a id="L29" href="/hemantrajput19/android-build-test/-/jobs/568550534#L29" class="gl-link d-inline-block text-right line-number flex-shrink-0">29</a> <span class="ws-pre-wrap">warning react-scripts &gt; webpack-dev-server &gt; chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.</span></div><div class="js-line log-line"><a id="L30" href="/hemantrajput19/android-build-test/-/jobs/568550534#L30" class="gl-link d-inline-block text-right line-number flex-shrink-0">30</a> <span class="ws-pre-wrap">warning react-scripts &gt; webpack-dev-server &gt; chokidar &gt; fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.</span></div><div class="js-line log-line"><a id="L31" href="/hemantrajput19/android-build-test/-/jobs/568550534#L31" class="gl-link d-inline-block text-right line-number flex-shrink-0">31</a> <span class="ws-pre-wrap">warning react-scripts &gt; babel-jest &gt; @jest/transform &gt; jest-haste-map &gt; fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.</span></div><div class="js-line log-line"><a id="L32" href="/hemantrajput19/android-build-test/-/jobs/568550534#L32" class="gl-link d-inline-block text-right line-number flex-shrink-0">32</a> <span class="ws-pre-wrap">warning react-scripts &gt; jest-environment-jsdom-fourteen &gt; jsdom &gt; request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142</span></div><div class="js-line log-line"><a id="L33" href="/hemantrajput19/android-build-test/-/jobs/568550534#L33" class="gl-link d-inline-block text-right line-number flex-shrink-0">33</a> <span class="ws-pre-wrap">warning react-scripts &gt; webpack &gt; watchpack &gt; watchpack-chokidar2 &gt; chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.</span></div><div class="js-line log-line"><a id="L34" href="/hemantrajput19/android-build-test/-/jobs/568550534#L34" class="gl-link d-inline-block text-right line-number flex-shrink-0">34</a> <span class="ws-pre-wrap">warning react-scripts &gt; jest &gt; jest-cli &gt; jest-config &gt; jest-environment-jsdom &gt; jsdom &gt; request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142</span></div><div class="js-line log-line"><a id="L35" href="/hemantrajput19/android-build-test/-/jobs/568550534#L35" class="gl-link d-inline-block text-right line-number flex-shrink-0">35</a> <span class="ws-pre-wrap">warning react-scripts &gt; jest &gt; jest-cli &gt; jest-config &gt; jest-environment-jsdom &gt; jsdom &gt; left-pad@1.3.0: use String.prototype.padStart()</span></div><div class="js-line log-line"><a id="L36" href="/hemantrajput19/android-build-test/-/jobs/568550534#L36" class="gl-link d-inline-block text-right line-number flex-shrink-0">36</a> <span class="ws-pre-wrap">warning react-scripts &gt; workbox-webpack-plugin &gt; workbox-build &gt; strip-comments &gt; babel-plugin-transform-object-rest-spread &gt; babel-runtime &gt; core-js@2.6.11: core-js@&lt;3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.</span></div><div class="js-line log-line"><a id="L37" href="/hemantrajput19/android-build-test/-/jobs/568550534#L37" class="gl-link d-inline-block text-right line-number flex-shrink-0">37</a> <span class="ws-pre-wrap">[2/4] Fetching packages...</span></div><div class="js-line log-line"><a id="L38" href="/hemantrajput19/android-build-test/-/jobs/568550534#L38" class="gl-link d-inline-block text-right line-number flex-shrink-0">38</a> <span class="ws-pre-wrap">info fsevents@2.1.2: The platform "linux" is incompatible with this module.</span></div><div class="js-line log-line"><a id="L39" href="/hemantrajput19/android-build-test/-/jobs/568550534#L39" class="gl-link d-inline-block text-right line-number flex-shrink-0">39</a> <span class="ws-pre-wrap">info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.</span></div><div class="js-line log-line"><a id="L40" href="/hemantrajput19/android-build-test/-/jobs/568550534#L40" class="gl-link d-inline-block text-right line-number flex-shrink-0">40</a> <span class="ws-pre-wrap">info fsevents@2.1.2: The engine "node" is incompatible with this module. Expected version "^8.16.0 || ^10.6.0 || &gt;=11.0.0".</span></div><div class="js-line log-line"><a id="L41" href="/hemantrajput19/android-build-test/-/jobs/568550534#L41" class="gl-link d-inline-block text-right line-number flex-shrink-0">41</a> <span class="ws-pre-wrap">error semver@7.3.2: The engine "node" is incompatible with this module. Expected version "&gt;=10".</span></div><div class="js-line log-line"><a id="L42" href="/hemantrajput19/android-build-test/-/jobs/568550534#L42" class="gl-link d-inline-block text-right line-number flex-shrink-0">42</a> <span class="ws-pre-wrap">error Found incompatible module</span></div><div class="js-line log-line"><a id="L43" href="/hemantrajput19/android-build-test/-/jobs/568550534#L43" class="gl-link d-inline-block text-right line-number flex-shrink-0">43</a> <span class="ws-pre-wrap">info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.</span></div></div><div><div role="button" class="log-line collapsible-line d-flex justify-content-between ws-normal"><svg aria-hidden="true" class="arrow position-absolute s16 ic-angle-down"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#angle-down"></use></svg> <a id="L44" href="/hemantrajput19/android-build-test/-/jobs/568550534#L44" class="gl-link d-inline-block text-right line-number flex-shrink-0">44</a> <span class="line-text w-100 ws-pre-wrap term-fg-l-cyan term-bold">Running after_script</span> <div class="log-duration-badge rounded align-self-start px-2 ml-2 flex-shrink-0 ws-normal">
  00:01
</div></div> </div><div><div role="button" class="log-line collapsible-line d-flex justify-content-between ws-normal"><svg aria-hidden="true" class="arrow position-absolute s16 ic-angle-right"><use xlink:href="https://gitlab.com/assets/icons-692a50bb8d7055b3f0337df7ee5be22653cf9a73380c2f3e3891c6c4a81733b0.svg#angle-right"></use></svg> <a id="L45" href="/hemantrajput19/android-build-test/-/jobs/568550534#L45" class="gl-link d-inline-block text-right line-number flex-shrink-0">45</a> <span class="line-text w-100 ws-pre-wrap term-fg-l-cyan term-bold">Uploading artifacts for failed job</span> <div class="log-duration-badge rounded align-self-start px-2 ml-2 flex-shrink-0 ws-normal">
  00:02
</div></div> </div><div class="js-line log-line"><a id="L46" href="/hemantrajput19/android-build-test/-/jobs/568550534#L46" class="gl-link d-inline-block text-right line-number flex-shrink-0">46</a> <span class="ws-pre-wrap term-fg-l-red term-bold">ERROR: Job failed: exit code 1</span></div> </code></div>

**Comment by postor** [comment]
I think it's ionic version issue, please try run `yarn global add ionic`
before your ionic build script

shvhh <notifications@github.com> 于2020年5月27日周三 上午5:02写道：
